services:
  - type: web
    name: capstone-hospital-app
    runtime: python
    region: oregon  # or keep default
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: super_secret_key
    plan: free  # Make sure you are using Free plan unless you want paid
